backend:
  name: github
  repo: jonathansgardner/netlify_test

media_folder: static/assets
public_folder: /assets

collections:
  - name: siteOptions
    label: "Site Options"
    files: 
      - name: siteHeader
        label: "Site Header"
        file: site/config/header.yml
        editor:
          preview: false
        fields:
          - { name: image, label: Image, widget: image }
          - name: siteBranding
            label: "Site Branding"
            widget: object
            fields: 
              - { name: logo, label: Logo, widget: image }
              - { name: siteTitle, label: "Site Title", widget: string }
              - { name: subtitle, label: Subtitle, widget: string }

      - name: homepage
        label: "Homepage"
        file: site/config/homepage.yml
        editor:
          preview: false
        fields:
          - name: about
            label: "About Page Preview"
            widget: object
            fields:
              - { name: hideSection, label: "Hide section", widget: boolean }
              - { name: heading, label: Heading, widget: string, required: false, hint: "Leave blank to use the About Page's heading" }
              - { name: content, label: "Content", widget: markdown, required: false, hint: "Leave blank to use the About Page's snippet" }
              - { name: linkText, label: "Link Text", widget: string, required: true }

          - name: services
            label: Services
            widget: object
            fields:
              - { name: hideSection, label: "Hide section", widget: boolean }
              - { name: heading, label: Heading, widget: string, required: true }
              - { name: content, label: "Content", widget: markdown, required: false }
              - name: services
                label: "Services"
                label_singular: "Service"
                widget: list
                field: { name: services, label: Services, label_singular: Service, widget: relation, collection: services, valueField: "title", displayFields: ["title"], searchFields: ["title"] }

          - name: featured
            label: "featured Content"
            widget: object
            fields:
              - { name: hideSection, label: "Hide section", widget: boolean }
              - { name: heading, label: Heading, widget: string, required: true }
              - { name: linkText, label: "Link Text", widget: string, required: true }

          - name: customSections
            label: "Custom Sections"
            label_singular: "Custom Section"
            widget: list
            typeKey: "Custom Section"
            types:
              - name: pagePreview
                label: "Page Preview"
                widget: object
                fields:
                  - name: page
                    label: Page
                    widget: relation
                    collection: pages
                    valueField: "title"
                    searchFields: [ "title" ]
                    displayFields: [ "title" ]
                  - { name: heading, label: Heading, widget: string, required: false, hint: "Leave blank to use the Page's heading" }
                  - { name: content, label: "Content", widget: markdown, required: false, hint: "Leave blank to use the Page's snippet" }
                  - { name: linkText, label: "Link Text", widget: string, required: true }
                  
              - name: pageThumbnails
                label: "Page Thumbnails"
                widget: object
                fields:
                  - { name: heading, label: Heading, widget: string, required: true }
                  - { name: content, label: "Content", widget: markdown, required: false }
                  - name: thumbnails
                    label: Thumbnails
                    label_singular: Thumbnail
                    widget: list
                    fields:
                      - name: pageLink
                        label: "Page To Link"
                        widget: relation
                        collection: pages
                        valueField: "title"
                        searchFields: [ "title" ]
                        displayFields: [ "title" ]
                      - { name: image, label: Image, widget: image, required: true }
                      - { name: heading, label: Heading, widget: string, required: false, hint: "Defaults to the Page's heading if left bank" }
                    
          - { name: showTestimonials, label: "Show Testimonials Section", widget: boolean }
          - { name: showContactForm, label: "Show Contact Form", widget: boolean }

      - name: footer
        label: Footer
        file: site/config/footer.yml
        editor:
          preview: false
        fields:
          - { name: copyright, label: "Copyright" }

  - name: pages
    label: Pages
    label_singular: Page
    folder: site/content/pages
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: header, label: Header, widget: string }
      - { name: content, label: Content, widget: markdown }

  - name: testimonials
    label: Testimonials
    label_singular: Testimonial
    folder: site/content/testimonials
    create: true
    identifier_field: author
    fields:
      - { name: recording, label: Recording, widget: file }
      - { name: author, label: Author, widget: string }
      - { name: hometown, label: Hometown, widget: string }
      - { name: quote, label: Quote, widget: text }

  - name: videos
    label: videos
    label_singular: Video
    folder: site/content/posts/videos
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: date }
      - { name: video, label: Video, widget: file }

  - name: services
    label: Services
    label_singular: Service
    folder: site/content/services
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: image, label: Image, widget: image }
      - { name: thumbnail, label: Thumbnail, widget: image, required: false }
      - { name: description, label: Description, widget: text }