backend:
  name: github
  repo: jonathansgardner/netlify_test

media_folder: static/assets
public_folder: /assets

collections:
  - name: siteOptions
    label: "Site Options"
    files: 
      - name: siteHeader
        label: "Site Header"
        file: site/config/header.yml
        fields:
          - { name: image, label: Image, widget: image }
          - name: siteBranding
            label: "Site Branding"
            widget: object
            fields: 
              - { name: logo, label: Logo, widget: image }
              - { name: siteTitle, label: "Site Title", widget: string }
              - { name: subtitle, label: Subtitle, widget: string }
            editor:
              preview: false
      - name: homepageSettings
        label: "Homepage Settings"
        file: site/config/homepage.yml
        fields:
          - { name: showAbout, label: "Show About Section", widget: boolean }
          - { name: showServices, label: "Show Services Section", widget: boolean }
          - { name: showFeatured, label: "Show Featured Content Section", widget: boolean }
          - { name: showTestimonials, label: "Show Testimonials Section", widget: boolean }
          - { name: showContactForm, Label: "Show Contact Form", widget: boolean }
        editor:
          preview: false
      - name: about
        label: About
        file: site/config/about.yml
        fields:
          - { name: header, label: Header, widget: string }
          - { name: snippet, label: Snippet, widget: markdown, required: false }
          - { name: content, label: Content, widget: markdown }
          - { name: linkText, label: "Link Text", widget: string }
        editor:
          preview: false
      - name: services
        label: Services
        file: site/config/services.yml
        fields:
          - { name: header, label: Header, widget: string }
          - { name: description, label: Description, widget: markdown, required: false }
          - name: service
            label: Service
            widget: relation
            collection: service
            displayFields: [ "name", "image", "thumbnail", "description" ]
            multiple: false
        editor:
          preview: false
      - name: featuredContent
        label: "Featured Content"
        file: site/config/featured.yml
        fields:
          - { name: header, label: Header, widget: string }
          - name: featured
            label: "Featured Content"
            widget: relation
          - { name: linkText, label: "Link Text", widget: string }
        editor:
          preview: false
      - name: testimonials
        label: Testimonials
        file: site/config/testimonials.yml
        fields:
          - { name: header, label: Header, widget: string }
          - { name: includeAudio, label: "Include Audio", widget: boolean }
        editor:
          preview: false
      - name: contactForm
        label: "Contact Form"
        file: site/config/contact.yml
        fields:
          - { name: header, label: Header, widget: string }
        editor:
          preview: false
      - name: footer
        label: Footer
        file: site/config/footer.yml
        fields:
          - { name: copyright, label: "Copyright" }
        editor:
          preview: false
  - name: testimonial
    label: Testimonial
    folder: site/content/testimonials
    create: true
    identifier_field: author
    fields:
      - { name: recording, label: Recording, widget: file }
      - { name: author, label: Author, widget: string }
      - { name: hometown, label: Hometown, widget: string }
      - { name: quote, label: Quote, widget: text }
  - name: video
    label: Video
    folder: site/content/posts/videos
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: date }
      - { name: video, label: Video, widget: file }
  - name: service
    label: Service
    folder: site/content/services
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: image, label: Image, widget: image }
      - { name: thumbnail, label: Thumbnail, widget: image, required: false }
      - { name: description, label: Description, widget: text }