backend:
  name: github
  repo: jonathansgardner/netlify_test

media_folder: static/assets
public_folder: /assets

collections:
  - name: siteOptions
    label: "Site Options"
    files: 
      - name: siteHeader
        label: "Site Header"
        file: site/config/header.yml
        fields:
          - { name: image, label: Image, widget: image }
          - name: siteBranding
            label: "Site Branding"
            widget: object
            fields: 
              - { name: logo, label: Logo, widget: image }
              - { name: siteTitle, label: "Site Title", widget: string }
              - { name: subtitle, label: Subtitle, widget: string }
            editor:
              preview: false
      - name: homepage
        label: "Homepage"
        file: site/config/homepage.yml
        fields:
          - name: section
            label: "Section"
            widget: list
            types:
              - name: pagePreview
                label: "Page Preview"
                widget: object
                fields:
                  - name: page
                    label: Page
                    widget: relation
                    collection: page
                    valueField: "title"
                    searchFields: [ "title" ]
                    displayFields: [ "title" ]
          - name: about
            label: "About Preview"
            widget: object
            fields:
              - { name: hideSection, label: "Hide section", widget: boolean }
              - { name: header, label: Header, widget: string, required: false, hint: "if left blank, header will default to the About Page's header" }
              - { name: content, label: "Content", widget: markdown, required: false, hint: "if left blank, content will be set from the About Page's body" }
              - { name: linkText, label: "Link Text", widget: string, required: true }
          - name: services
            label: "Services"
            widget: object
            fields:
              - { name: hideSection, label: "Hide section", widget: boolean }
              - { name: header, label: Header, widget: string, required: true }
              - { name: content, label: "Content", widget: markdown, required: false, hint: "if left blank, content will be set from the About Page's body" }
          - { name: showFeatured, label: "Show Featured Content Section", widget: boolean }
          - { name: showTestimonials, label: "Show Testimonials Section", widget: boolean }
          - { name: showContactForm, Label: "Show Contact Form", widget: boolean }
        editor:
          preview: false
      - name: services
        label: Services
        file: site/config/services.yml
        fields:
          - { name: header, label: Header, widget: string }
          - { name: description, label: Description, widget: markdown, required: false }
          - name: service
            label: Service
            widget: relation
            collection: service
            displayFields: [ "name", "image", "thumbnail", "description" ]
            multiple: false
        editor:
          preview: false
      - name: featuredContent
        label: "Featured Content"
        file: site/config/featured.yml
        fields:
          - { name: header, label: Header, widget: string }
          - name: featured
            label: "Featured Content"
            widget: relation
          - { name: linkText, label: "Link Text", widget: string }
        editor:
          preview: false
      - name: testimonials
        label: Testimonials
        file: site/config/testimonials.yml
        fields:
          - { name: header, label: Header, widget: string }
          - { name: includeAudio, label: "Include Audio", widget: boolean }
        editor:
          preview: false
      - name: contactForm
        label: "Contact Form"
        file: site/config/contact.yml
        fields:
          - { name: header, label: Header, widget: string }
        editor:
          preview: false
      - name: footer
        label: Footer
        file: site/config/footer.yml
        fields:
          - { name: copyright, label: "Copyright" }
        editor:
          preview: false
  - name: page
    label: Page
    folder: site/content/pages
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: header, label: Header, widget: string }
      - { name: content, label: Content, widget: markdown }
  - name: thumbnailStyle
    label: Thumbnail Style
    folder: site/content/thumbnailStyle
    create: false
    fields:
      - { name: title, label: Title, widget: string }
  - name: testimonial
    label: Testimonial
    folder: site/content/testimonials
    create: true
    identifier_field: author
    fields:
      - { name: recording, label: Recording, widget: file }
      - { name: author, label: Author, widget: string }
      - { name: hometown, label: Hometown, widget: string }
      - { name: quote, label: Quote, widget: text }
  - name: video
    label: Video
    folder: site/content/posts/videos
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: date }
      - { name: video, label: Video, widget: file }
  - name: service
    label: Service
    folder: site/content/services
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: image, label: Image, widget: image }
      - { name: thumbnail, label: Thumbnail, widget: image, required: false }
      - { name: description, label: Description, widget: text }