backend:
  name: github
  repo: jonathansgardner/netlify_test

media_folder: static/assets
public_folder: /assets

collections:
  - name: settings
    label: "Settings"
    files: 
      - name: siteIdentity
        label: "Site Identity"
        file: src/settings/identity.yml
        editor:
          preview: false
        fields:
          - name: siteIdentity
            label: "Site Identity"
            widget: object
            fields: 
              - { name: logo, label: Logo, widget: image, required: false }
              - { name: siteTitle, label: "Site Title", widget: string }
              - { name: slogan, label: Slogan, widget: string, required: false }
              - { name: icon, label: Icon, widget: image, required: false } # will need validation
              - { name: copyright, label: "Copyright", required: false }

      - name: homepage
        label: "Homepage"
        file: src/settings/homepage.yml
        editor:
          preview: false
        fields:
          - name: sections
            label: "Sections"
            label_singular: "Section"
            widget: list
            typeKey: "Section"
            types:
              - name: pagePreview
                label: "Page Preview"
                widget: object
                fields:
                  - name: page
                    label: Page
                    widget: relation
                    collection: pages
                    valueField: "title"
                    searchFields: [ "title" ]
                    displayFields: [ "title" ]
                  - { name: heading, label: Heading, widget: string, required: false, hint: "Defaults to the Page's heading if no value is entered." }
                  - name: content
                    label: "Content"
                    widget: markdown
                    buttons: ["bold", "italic", "code", "link", "quote", "code-block", "bulleted-list", "numbered-list"]
                    required: false
                    hint: "Defaults to the Page's snippet if no value is entered."
                  - { name: linkText, label: "Link Text", widget: string, required: true }

              - name: pageThumbnails
                label: "Page Thumbnails"
                widget: object
                fields:
                  - { name: heading, label: Heading, widget: string, required: true }
                  - name: content
                    label: "Content"
                    widget: markdown
                    buttons: ["bold", "italic", "code", "link", "quote", "code-block", "bulleted-list", "numbered-list"]
                    required: false
                  - name: thumbnails
                    label: Thumbnails
                    label_singular: Thumbnail
                    widget: list
                    fields:
                      - name: pageLink
                        label: "Page To Link"
                        widget: relation
                        collection: pages
                        valueField: "title"
                        searchFields: [ "title" ]
                        displayFields: [ "title" ]
                      - { name: image, label: Image, widget: image, required: true }
                      - { name: heading, label: Heading, widget: string, required: false, hint: "Defaults to the Page's heading if no value is entered." }

              - name: featuredContent
                label: "Featured Content"
                widget: object
                fields:
                  - { name: heading, label: Heading, widget: string }
                  - name: content
                    label: Content
                    widget: list
                    types:
                      - name: article
                        label: Article
                        widget: relation
                        collection: articles
                        valueField: "title"
                        searchFields: [ "title" ]
                        displayFields: [ "title" ]
                      - name: video
                        label: Video
                        widget: relation
                        collection: videos
                        valueField: "title"
                        searchFields: [ "title" ]
                        displayFields: [ "title" ]
                  - name: layout
                    label: Layout
                    widget: select
                    options:
                      - { label: List, value: list }
                      - { label: Grid, value: grid }
                  - { name: linkText, label: "Link Text", widget: string }

              - name: recentContent
                label: "Recent Content"
                widget: object
                fields:
                  - { name: heading, label: Heading, widget: string }
                  - name: contentType
                    label: "Content Type"
                    widget: select
                    default: video
                    options:
                      - { label: Articles, value: articles }
                      - { label: Videos, value: videos }
                  - { name: quantity, label: Quantity, widget: number }
                  - name: layout
                    label: Layout
                    widget: select
                    options:
                      - { label: List, value: list }
                      - { label: Grid, value: grid }
                  - { name: linkText, label: "Link Text", widget: string }
                    
          - { name: showTestimonials, label: "Show Testimonials", widget: boolean }
          - { name: showContactForm, label: "Show Contact Form", widget: boolean }

      - name: panels
        label: Panels
        file: src/settings/panels.yml
        editor:
          preview: false
        fields:
          - name: testimonials
            label: Testimonials
            widget: object
            fields:
              - { name: heading, label: Heading, widget: string, required: false, hint: "Defaults to \"Testimonials\" if no value is entered."}
              - { name: includeAudio, label: "Include Audio", widget: boolean }

          - name: contactForm
            label: "Contact Form"
            widget: object
            fields:
              - { name: heading, label: Heading, widget: string, required: false, hint: "Defaults to \"Leave a Message\" if no value is entered." }
              - name: formFields
                label: Form Fields
                widget: list
                types:
                  - name: textInput
                    label: Text
                    widget: object
                    fields:
                      - { name: title, label: Title, widget: string }
                      - { name: label, label: Label, widget: string }
                  - name: emailInput
                    label: Email
                    widget: object
                    fields:
                      - { name: title, label: Title, widget: string }
                      - { name: label, label: Label, widget: string }
                  - name: phoneInput
                    label: Phone
                    widget: object
                    fields:
                      - { name: title, label: Title, widget: string }
                      - { name: label, label: Label, widget: string }
                  - name: websiteInput
                    label: Website
                    widget: object
                    fields:
                      - { name: title, label: Title, widget: string }
                      - { name: label, label: Label, widget: string }
                  - name: checkbox
                    label: Checkbox
                    widget: object
                    fields:
                      - { name: title, label: Title, widget: string }
                      - { name: label, label: Label, widget: string }
                  - name: dropdown
                    label: Dropdown
                    widget: object
                    fields:
                      - { name: title, label: Title, widget: string }
                      - { name: label, label: Label, widget: string }
                      - name: options
                        label: Options
                        widget: list
                        fields:
                          - { name: option, label: Option, widget: string }
                          - { name: label, label: Label, widget: string }
                  - name: paragraph
                    label: Paragraph
                    widget: object
                    fields:
                      - { name: title, label: Title, widget: string }
                      - { name: label, label: Label, widget: string }
              - { name: buttonText, label: "Button Text", widget: string, required: false, hint: "Defaults to \"Submit\" if no value is entered." }

  - name: pages
    label: Pages
    label_singular: Page
    folder: src/content/pages
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: heading, label: Heading, widget: string }
      - { name: featuredImage, label: "Featured Image", widget: image, required: false }
      - { name: content, label: Content, widget: markdown }
      - name: snippet
        label: Snippet
        widget: markdown
        buttons: ["bold", "italic", "code", "link", "quote", "code-block", "bulleted-list", "numbered-list"]
        hint: "A preview or brief overview of this page's content. Used when a Page Preview section of this page is added to another page"

  - name: testimonials
    label: Testimonials
    label_singular: Testimonial
    folder: src/content/testimonials
    create: true
    identifier_field: author
    fields:
      - { name: title, label: Title, widget: string }
      - { name: recording, label: Recording, widget: file, required: false }
      - { name: quote, label: Quote, widget: text }
      - { name: author, label: Author, widget: string }
      - { name: hometown, label: Hometown, widget: string }

  - name: articles
    label: Articles
    label_singular: Article
    folder: src/content/posts/articles
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: heading, label: Heading, widget: string }
      - { name: featuredImage, label: "Featured Image", widget: image, required: false }
      - { name: content, label: Content, widget: markdown }
      - name: snippet
        label: Snippet
        widget: markdown
        buttons: ["bold", "italic", "code", "link", "quote", "code-block", "bulleted-list", "numbered-list"]
        hint: "A preview or brief overview of this article's content. Used when the article is included in a recent or featured content section of another page"

  - name: videos
    label: Videos
    label_singular: Video
    folder: src/content/posts/videos
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: date }
      - { name: video, label: Video, widget: file }
      - { name: description, label: Description, widget: text, required: false }
